export let transactions = [
  {
    id: 0,
    transactionType: "Expenses",
    transactionsubType: "Office Supplies",
    account: "Cash in Hand",
    accountType: "Investors Money",
    amount: 600,
    currency: "AED",
    date: "25-01-2020",
  },
  {
    id: 1,
    transactionType: "Sales",
    transactionsubType: "Invoice 10293",
    account: "Cash in Hand",
    accountType: "Bank Transfer",
    amount: 1203,
    currency: "AED",
    date: "05-02-2021",
  },
  {
    id: 2,
    transactionType: "Expenses",
    transactionsubType: "Professional Fees",
    account: "Cash in Hand",
    accountType: "Investors Money",
    amount: 2778,
    currency: "EUR",
    date: "13-01-2020",
  },
  {
    id: 3,
    transactionType: "Sales",
    transactionsubType: "Invoice 2838",
    account: "Cash in Hand",
    accountType: "Investors Money",
    amount: 12500,
    currency: "USD",
    date: "25-12-2020",
  },
];
